language: ruby
sudo: false
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.0.beta1.gemfile
matrix:
  exclude:
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6.0.0.beta1.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.0.beta1.gemfile
  fast_finish: true
